# Service
apiVersion: v1
kind: Service
metadata:
  name: weatherapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: weatherapp
  selector:
    app: weatherapp

---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weatherapp
  labels:
    chart: "weatherapp-0.1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: "brahmini/weatherapp:1.0.1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi